## C & T tables scaling/transformation script for use in deconvolution methods
##
## @zgr2788
##
## Description:
##
## Includes 4 rules, depending on seeded unseeded and scale first or transform
## first.
##
##
##
##
##
##
##
##
##
##
##
##

#First scale then transform
rule scaleTransform_T:
    input:
        T_table = 'Tissue_splits/{sample}-{tissue}-fpkms.rds'

    output:
        'Tissue_splits/Normalized_tables/{sample}-{tissue}-fpkms_scaled.rds',

    conda:
        'env.yaml'

    params:
        # scaleTMethod = config['stParam']['scaleT'],
        # scaleCMethod = config['stParam']['scaleC'],
        # transMethod = config['stParam']['transform']
        scaleTMethod = 'TMM',
        scaleCMethod = 'SCTransform',
        transMethod = 'none'


    #threads: config["cores"]["scaleTransform"]
    threads: 32

    #benchmark:
     #   "Benchmarks/{sample}_Scaletransform_benchmark.txt"

    #resources:
       # mem_mb=getMB(config['mem_gb']['scaleTransform'])

    shell:
        """
        mkdir -p Tissue_splits/Normalized_tables
        Rscript Modules/Scale_T/scaleTable_T.R {input.T_table} {params.scaleTMethod} {threads}
        """



# #######################
# #######################
# #######################

# #Same rules with seeded keyword
# rule scaleTransformSeeded_T_C:
#     input:
#         C_table = 'Input/References/{sample}_C0_seeded.rds',
#         C_phenData = 'Input/References/{sample}_phenData_seeded.rds',
#         T_table = 'Input/Psuedobulks/{sample}_pbulks_seeded.rds'

#     output:
#         'Input/Normalized_tables/{sample}_pbulks_seeded_scaled_transformed.rds',
#         'Input/Normalized_tables/{sample}_C0_seeded_scaled_transformed.rds'

#     conda:
#         'env.yaml'

#     params:
#         scaleTMethod = config['stParam']['scaleT'],
#         scaleCMethod = config['stParam']['scaleC'],
#         transMethod = config['stParam']['transform']

#     threads: config["cores"]["scaleTransform"]

#     benchmark:
#         "Benchmarks/{sample}_Scaletransform_benchmark.txt"

#     resources:
#         mem_mb=getMB(config['mem_gb']['scaleTransform'])

#     shell:
#         """
#         mkdir -p Input/Normalized_tables
#         Rscript Modules/Scale_transform/scaleTable_T.R {input.T_table} {params.scaleTMethod} {threads}
#         Rscript Modules/Scale_transform/scaleTable_C.R {input.C_table} {input.C_phenData} {params.scaleCMethod} {threads}
#         Rscript Modules/Scale_transform/transformTables.R Input/Normalized_tables/{wildcards.sample}_pbulks_seeded_scaled.rds Input/Normalized_tables/{wildcards.sample}_C0_seeded_scaled.rds {params.transMethod} {threads}
#         """


# #First transform then scale
# rule transformScaleSeeded_T_C:
#     input:
#         C_table = 'Input/References/{sample}_C0_seeded.rds',
#         C_phenData = 'Input/References/{sample}_phenData_seeded.rds',
#         T_table = 'Input/Psuedobulks/{sample}_pbulks_seeded.rds'

#     output:
#         'Input/Normalized_tables/{sample}_pbulks_seeded_transformed_scaled.rds',
#         'Input/Normalized_tables/{sample}_C0_seeded_transformed_scaled.rds'

#     conda:
#         'env.yaml'

#     params:
#         scaleTMethod = config['stParam']['scaleT'],
#         scaleCMethod = config['stParam']['scaleC'],
#         transMethod = config['stParam']['transform']

#     threads: config["cores"]["scaleTransform"]

#     benchmark:
#         "Benchmarks/{sample}_Scaletransform_benchmark.txt"

#     resources:
#         mem_mb=getMB(config['mem_gb']['scaleTransform'])

#     shell:
#         """
#         mkdir -p Input/Normalized_tables
#         Rscript Modules/Scale_transform/transformTables.R {input.T_table} {input.C_table} {params.transMethod} {threads}
#         Rscript Modules/Scale_transform/scaleTable_T.R Input/Normalized_tables/{wildcards.sample}_pbulks_seeded_transformed.rds {params.scaleTMethod} {threads}
#         Rscript Modules/Scale_transform/scaleTable_C.R Input/Normalized_tables/{wildcards.sample}_C0_seeded_transformed.rds {input.C_phenData} {params.scaleCMethod} {threads}
#         """
